# Enable BLE
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BLE_MOUSE=y

# Enable pointing device support
CONFIG_ZMK_POINTING_DEVICE=y

# Disable keyboard
CONFIG_ZMK_KEYBOARD=y
CONFIG_ZMK_USB_DEVICE_HID_KEYBOARD=n

# Enable PMW3360 driver
CONFIG_PMW3360=y

# Optional: logging
CONFIG_LOG=y
